/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.codeimpact.ui.report.drilldown;

import com.codeimpact.data.JDBCUtils;
import com.codeimpact.ui.abstraction.ReportIFrame;
import com.codeimpact.util.AppUtils;
import java.util.HashMap;
import java.util.List;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRPrintHyperlink;
import net.sf.jasperreports.engine.JRPrintHyperlinkParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JRHyperlinkListener;

/**
 *
 * @author eko
 */
public class FrmChartSale extends ReportIFrame implements JRHyperlinkListener {

    private HashMap parameterMap;
    private String reportBaseDir = AppUtils.getInstance().getReportPath() + AppUtils.getInstance().getFileSeparator();
    private boolean hyperlinkMode = false;

    /**
     * Creates new form FrmChartSale
     */
    public FrmChartSale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPreview1 = new com.codeimpact.ui.swing.BtnPreview();
        btnPrint1 = new com.codeimpact.ui.swing.BtnPrint();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Chart Sale");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        btnPreview1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreview1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPreview1);

        btnPrint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrint1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrint1ActionPerformed
        printReport();
    }//GEN-LAST:event_btnPrint1ActionPerformed

    private void btnPreview1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreview1ActionPerformed
        viewReport();
    }//GEN-LAST:event_btnPreview1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.codeimpact.ui.swing.BtnPreview btnPreview1;
    private com.codeimpact.ui.swing.BtnPrint btnPrint1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void prepareReport() throws Exception {
        String reportFile = reportBaseDir + (hyperlinkMode ? "ListSalesPerBP.jrxml" : "ChartSale.jrxml");
        JasperReport jasperReport = JasperCompileManager.compileReport(reportFile);
        jasperPrint = JasperFillManager.fillReport(jasperReport, parameterMap, JDBCUtils.getInstance().getConnection());
        if (hyperlinkMode) {
            hyperlinkMode = false;
        }
    }

    @Override
    public void registerHyperlinkListener() {
        jasperViewer.getJRViewer().addHyperlinkListener(this);
    }

    @Override
    public void gotoHyperlink(JRPrintHyperlink hyperlink) throws JRException {
        parameterMap = new HashMap();
        List<JRPrintHyperlinkParameter> parameters = hyperlink.getHyperlinkParameters().getParameters();
        for (JRPrintHyperlinkParameter parameter : parameters) {
            parameterMap.put(parameter.getName(), parameter.getValue());
        }
        hyperlinkMode = true;
        viewReport(this.getTitle() + " | Daftar Penjualan");
    }
}
